### ISSUE TITLE
HACS does not find Repo/Integration

### ISSUE THREAD

**Issue by h4nnes** [marq24/ha-senec-v3#21]
Hi,
any idea why I can’t find the integration in hacs, when I search for „Senec“?

The custom repo was added:

![IMG_9985](https://github.com/marq24/ha-senec-v3/assets/74971371/8de011ae-0ec2-4e75-bf4c-7be1ca9087da)

Thanks!
Hannes

PS: Manual adding was possible, but I would like to use the repo to get updates etc.

**Comment by marq24** [comment]
well - more or less I am clueless here - when you added he repro in HACS and then installed the custom_integration from this repro in HACS, then the SENEC.Home "should" appear under Devices and Services... But if after the installation in HACS the custom integration would not appear in HACS itself, then I am clueless what would be the root cause... 

![image](https://github.com/marq24/ha-senec-v3/assets/8012359/9a5b68cb-e9c3-4dd6-bd8b-139c2016505b)

**Comment by h4nnes** [comment]
I can’t download/find the repo in hacs. But it’s saying, the custom repo exists. Really strange

**Comment by marq24** [comment]
well - so when you have the repo added, then (adding another one) should/will look like this:
![image](https://github.com/marq24/ha-senec-v3/assets/8012359/3b6dfce4-751c-4d1a-9406-d6765e996dff)

and when you then press the blue (at the bottom) `Explore & Download Repositories` button and then type 'senec' in the search bar you should get the two possible HACS-Integrations [the 'original' version and "this" one here...]
![image](https://github.com/marq24/ha-senec-v3/assets/8012359/31121f4b-32cc-4f23-ade5-87570279a9de)

After you have selected `SENEC.Home V2.x/V3/V4 Systems` from this list, you need to press again the blue `download` button at the bottom/right... to finally install the custom integration in HA...

**Comment by marq24** [comment]
... but could it be, that you are using a "beta" version of HACS? - since the error message reports, that this repo is already part of the default store... 

But this PR 'https://github.com/hacs/default/pull/2035' is not merged yet - so I don't understand how ha-senec-v3 could be already in your hacs installation?

**Comment by h4nnes** [comment]
I'm using HACS version "1.32.1". But yes, looks different to your version. Which version are you using?
![grafik](https://github.com/marq24/ha-senec-v3/assets/74971371/e65b1207-2ead-4e50-8d62-3ea1369049e0)

When I search for Senec, I only get the repo from mchwalisz.

Really strange

**Comment by h4nnes** [comment]
So, I just reinstalled hacs and it's working now. Thanks a lot!
