### ISSUE TITLE
Add Inverter v3 Duo

### ISSUE THREAD

**Issue by Roka1997** [marq24/ha-senec-v3#83]
Hello, I have added the inverter according to the instructions.

Unfortunately, I get the following error message.

![Screenshot_20240310-203424_Home Assistant](https://github.com/marq24/ha-senec-v3/assets/149274319/b62872b7-8d4d-4bb6-8fc0-e748221fa684)

Where could the error be?

**Comment by marq24** [comment]
can you please provide the debug log output? https://github.com/marq24/ha-senec-v3/blob/master/docs/HA_DEBUG.md

**Comment by Roka1997** [comment]
Thanks für answer, here ist the log:

"Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.senec
Quelle: helpers/update_coordinator.py:331
Integration: SENEC.Home (Dokumentation, Probleme)
Erstmals aufgetreten: 22:12:43 (9 Vorkommnisse)
Zuletzt protokolliert: 22:18:10

Error requesting senec data: 404, message='Not found', url=URL('http://192.168.xxx.xxx/lala.cgi')"

I've edit the url with "x"

**Comment by marq24** [comment]
looks like you did not select `Internal inverter build into SENEC.Home V3 hybrid/hybrid duo` from the initial selection list when starting to configure the new device - when you did, then I would really need the full DEBUG log as described in my link above...

**Comment by Roka1997** [comment]
Hello, I think I have taken the correct entry.

![Screenshot_20240311-095306_Home Assistant](https://github.com/marq24/ha-senec-v3/assets/149274319/b87b6d82-fbe3-48f8-bde1-09b41be5f0f1)

Sorry for the wrong log, here is the correct one.

[error_log-2.txt](https://github.com/marq24/ha-senec-v3/files/14555954/error_log-2.txt)

**Comment by marq24** [comment]
`2024-03-10 22:11:31.388 WARNING (MainThread) [homeassistant.const] ENERGY_KILO_WATT_HOUR was used from senec, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfEnergy.KILO_WATT_HOUR instead, please create a bug report at https://github.com/marq24/ha-senec-v3/issues`

please update to the latest version of the integration - this was fixed in JAN - https://github.com/marq24/ha-senec-v3/issues/68 - we are already on '[2024.3.0](https://github.com/marq24/ha-senec-v3/tree/2024.3.0)'

**Comment by Roka1997** [comment]
I have solved it. Many thanks for the Help.
